### ISSUE TITLE
Table does not repsond after some time

### ISSUE THREAD

**Issue by b3nd3rit** [ivanwick/bekantfirmware#6]
I have flashed the latest firmware and everything works as expected.

But sometimes the controller does not react to the buttons.
After unpluging the power cord, wait some time and plug it in again, the table is working again.

Is there a deep sleep mode ?

**Comment by Kulimeya** [comment]
I have the same problem. Sometimes it doesn't do anything when I push both buttons. After a manual height adjustment by pressing one button it works again. Hope that can be fixed because otherwise it's perfect.
Edit: It helps sometimes, but not always. Sometimes some more adjustments are needed until it works again, or a second or third press of both buttons. Didn't see any pattern yet. But often it just does nothing when pressing both.

Edit: I got the instructions wrong. I thought it is more like a toggle where you just push both buttons and it goes to the opposite height, but you have to hold the button of the direction you want to go and then push the second one and let both go.

**Comment by ivanwick** [comment]
@Kulimeya Thanks for your usability report. I added a description of the button gestures to the [Installation Guide](https://github.com/ivanwick/bekantfirmware/wiki/Installation-Guide#test-new-firmware) to make it more visible there as well.

@b3nd3rit Are you still experiencing the problem with unresponsive buttons? There is no deep sleep mode. In fact as long as the control box is connected and powered, it is constantly sending signals to the legs even when nothing is moving.

It would be challenging to debug this remotely unless you have LIN signal traces of the failure case (requires a logic analyzer, see [sigrok plugins](https://github.com/ivanwick/bekantfirmware/tree/master/sigrok)). If you have any more information, we can collect it here. For example, how long after power cycling does it stop working and is it consistent? Did you have any problems with the OEM firmware? Does your BEKANT have one of the original faulty power supplies?

The firmware does start up in a "scan" mode where it syncs and initializes the legs. Usually it takes less than 1 sec but there is a loop to keep trying until the legs respond correctly before moving to normal operation. It does not take any button input while scanning. So my only guess is that the PIC might be reverting to the scan mode somehow (watchdog? other reset?), which desyncs it from the legs and it can't recover until everything is power cycled.

I certainly have not taken all error conditions into account in the firmware because I only have one BEKANT desk to test on, and the released firmware is what works for me. If this cannot be solved, I recommend restoring the OEM firmware or checking out one of the other BEKANT controller projects.

**Comment by Kulimeya** [comment]
Nice that's probably helpful. Big thanks for your work btw, I still runs perfect. I even flashed some friends desks.
